name: awecon
description: An application that automatically adjusts the temperature of a room using aruduino
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
